version: '3.8'

services:
  backend:  # ✅ Backend should be defined first
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: secure-file-backend
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

  frontend:  # ✅ Frontend comes after backend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: secure-file-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8000
    depends_on:
      - backend  # ✅ Ensures backend starts first
