# Generated by Django 5.1.5 on 2025-02-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesharinginfo',
            name='sender',
            field=models.EmailField(default=345678, max_length=255),
            preserve_default=False,
        ),
    ]
