# Generated by Django 5.1.5 on 2025-01-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptedfile',
            name='filename',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
