# Generated by Django 5.1.5 on 2025-02-08 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_filesharinginfo_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptedfile',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encrypted_files', to='backend_app.user', to_field='email'),
        ),
        migrations.AlterField(
            model_name='filesharinginfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_sharing_info', to='backend_app.user', to_field='email'),
        ),
    ]
