# Generated by Django 5.1.5 on 2025-02-08 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0003_alter_encryptedfile_email_alter_filesharinginfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptedfile',
            name='filename',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='filesharinginfo',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_sharing_info', to='backend_app.encryptedfile', to_field='filename'),
        ),
    ]
